package com.dsi.builder.front;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;



/*
 *

To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Diego Delgado
 */
public class reportesEnTiempoDePedido extends javax.swing.JFrame {

    /**
     * Creates new form reportesEnTiempoDePedido
     */
    public reportesEnTiempoDePedido() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFileChooser1 = new javax.swing.JFileChooser();
        jFileChooser2 = new javax.swing.JFileChooser();
        CheckCancelado = new javax.swing.JCheckBox();
        TxtFechaInicio = new javax.swing.JTextField();
        TxtFechaFin = new javax.swing.JTextField();
        CheckNotificado = new javax.swing.JCheckBox();
        CheckEntregado = new javax.swing.JCheckBox();
        CheckPendientePreparacion = new javax.swing.JCheckBox();
        CheckEnPreparacion = new javax.swing.JCheckBox();
        CheckListoParaServir = new javax.swing.JCheckBox();
        CheckPlantaBaja = new javax.swing.JCheckBox();
        CheckPrimerPiso = new javax.swing.JCheckBox();
        CheckSegundoPiso = new javax.swing.JCheckBox();
        BtnVisualizarSectorPiso = new javax.swing.JButton();
        BtnTotalizarPiso = new javax.swing.JButton();
        BtnTotalizarSector = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CheckCancelado.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        CheckCancelado.setForeground(new java.awt.Color(255, 255, 255));
        CheckCancelado.setSelected(true);
        CheckCancelado.setText("Cancelado");
        CheckCancelado.setAutoscrolls(true);
        CheckCancelado.setOpaque(false);
        CheckCancelado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckCanceladoActionPerformed(evt);
            }
        });
        getContentPane().add(CheckCancelado, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, -1));

        TxtFechaInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFechaInicioActionPerformed(evt);
            }
        });
        getContentPane().add(TxtFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 150, 30));

        TxtFechaFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFechaFinActionPerformed(evt);
            }
        });
        getContentPane().add(TxtFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 150, 30));

        CheckNotificado.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        CheckNotificado.setForeground(new java.awt.Color(255, 255, 255));
        CheckNotificado.setSelected(true);
        CheckNotificado.setText("Notificado");
        CheckNotificado.setOpaque(false);
        CheckNotificado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckNotificadoActionPerformed(evt);
            }
        });
        getContentPane().add(CheckNotificado, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, -1, -1));

        CheckEntregado.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        CheckEntregado.setForeground(new java.awt.Color(255, 255, 255));
        CheckEntregado.setSelected(true);
        CheckEntregado.setText("Entregado");
        CheckEntregado.setToolTipText("");
        CheckEntregado.setOpaque(false);
        CheckEntregado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckEntregadoActionPerformed(evt);
            }
        });
        getContentPane().add(CheckEntregado, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, -1, -1));

        CheckPendientePreparacion.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        CheckPendientePreparacion.setForeground(new java.awt.Color(255, 255, 255));
        CheckPendientePreparacion.setSelected(true);
        CheckPendientePreparacion.setText("Pendiente Preparación");
        CheckPendientePreparacion.setActionCommand("");
        CheckPendientePreparacion.setOpaque(false);
        CheckPendientePreparacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckPendientePreparacionActionPerformed(evt);
            }
        });
        getContentPane().add(CheckPendientePreparacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 200, -1));

        CheckEnPreparacion.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        CheckEnPreparacion.setForeground(new java.awt.Color(255, 255, 255));
        CheckEnPreparacion.setSelected(true);
        CheckEnPreparacion.setText("En Preparación");
        CheckEnPreparacion.setOpaque(false);
        CheckEnPreparacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckEnPreparacionActionPerformed(evt);
            }
        });
        getContentPane().add(CheckEnPreparacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, -1, -1));

        CheckListoParaServir.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        CheckListoParaServir.setForeground(new java.awt.Color(255, 255, 255));
        CheckListoParaServir.setSelected(true);
        CheckListoParaServir.setText("Listo Para Servir");
        CheckListoParaServir.setToolTipText("");
        CheckListoParaServir.setOpaque(false);
        CheckListoParaServir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckListoParaServirActionPerformed(evt);
            }
        });
        getContentPane().add(CheckListoParaServir, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, -1, -1));

        CheckPlantaBaja.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        CheckPlantaBaja.setForeground(new java.awt.Color(255, 255, 255));
        CheckPlantaBaja.setSelected(true);
        CheckPlantaBaja.setText("Planta Baja");
        CheckPlantaBaja.setOpaque(false);
        CheckPlantaBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckPlantaBajaActionPerformed(evt);
            }
        });
        getContentPane().add(CheckPlantaBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, -1, -1));

        CheckPrimerPiso.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        CheckPrimerPiso.setForeground(new java.awt.Color(255, 255, 255));
        CheckPrimerPiso.setSelected(true);
        CheckPrimerPiso.setText("Primer Piso");
        CheckPrimerPiso.setOpaque(false);
        CheckPrimerPiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckPrimerPisoActionPerformed(evt);
            }
        });
        getContentPane().add(CheckPrimerPiso, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, -1, -1));

        CheckSegundoPiso.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        CheckSegundoPiso.setForeground(new java.awt.Color(255, 255, 255));
        CheckSegundoPiso.setSelected(true);
        CheckSegundoPiso.setText("Segundo Piso");
        CheckSegundoPiso.setOpaque(false);
        CheckSegundoPiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckSegundoPisoActionPerformed(evt);
            }
        });
        getContentPane().add(CheckSegundoPiso, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, -1, -1));

        BtnVisualizarSectorPiso.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        BtnVisualizarSectorPiso.setText("Visualizar Sector por Piso");
        BtnVisualizarSectorPiso.setEnabled(false);
        getContentPane().add(BtnVisualizarSectorPiso, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, -1, -1));

        BtnTotalizarPiso.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        BtnTotalizarPiso.setText("Totalizar por Piso");
        BtnTotalizarPiso.setMaximumSize(new java.awt.Dimension(179, 31));
        BtnTotalizarPiso.setMinimumSize(new java.awt.Dimension(179, 31));
        BtnTotalizarPiso.setPreferredSize(new java.awt.Dimension(179, 31));
        BtnTotalizarPiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTotalizarPisoActionPerformed(evt);
            }
        });
        getContentPane().add(BtnTotalizarPiso, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 197, -1));

        BtnTotalizarSector.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        BtnTotalizarSector.setText("Totalizar por Sector");
        getContentPane().add(BtnTotalizarSector, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 197, -1));

        BtnSalir.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, 197, -1));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("de Pedido");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 510, 61));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Periodo inicial");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 180, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Periodo final");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 200, -1));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Estados del pedido");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Pisos");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, -1, -1));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Reportes en tiempos");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 510, 61));

        jLabel8.setIcon(new javax.swing.ImageIcon("D:\\Imagenes\\MAPS.png")); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 40, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon("D:\\Imagenes\\LOGIN.png")); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 50, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\Imagenes\\FONDO.jpeg")); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CheckListoParaServirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckListoParaServirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckListoParaServirActionPerformed

    private void CheckNotificadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckNotificadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckNotificadoActionPerformed

    private void CheckEntregadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckEntregadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckEntregadoActionPerformed

    private void CheckPendientePreparacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckPendientePreparacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckPendientePreparacionActionPerformed

    private void CheckCanceladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckCanceladoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckCanceladoActionPerformed

    private void CheckSegundoPisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckSegundoPisoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckSegundoPisoActionPerformed

    private void CheckEnPreparacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckEnPreparacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckEnPreparacionActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
         if (JOptionPane.showConfirmDialog(rootPane, "¿Desea realmente salir de la Generación de Reportes?",
                "Salir de la generación de Reportes", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
            System.exit(0);
        
        
       //dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void CheckPlantaBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckPlantaBajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckPlantaBajaActionPerformed

    private void CheckPrimerPisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckPrimerPisoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckPrimerPisoActionPerformed

    private void BtnTotalizarPisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTotalizarPisoActionPerformed
                String PeriodoInicial;
                String PeriodoFinal;
                
                PeriodoInicial = TxtFechaInicio.getText();
		PeriodoFinal = TxtFechaFin.getText();
                if (PeriodoInicial.equals("") || PeriodoFinal.equals("") ){
                    javax.swing.JOptionPane mensaje = new javax.swing.JOptionPane();
                mensaje.showMessageDialog(null, "Falta ingresar alguna fecha", "Error al ingresar fecha", mensaje.ERROR_MESSAGE);
                }
                else {
                    if (Date.parse(TxtFechaInicio.getText())<= Date.parse(TxtFechaFin.getText()) )
               {  
		//PeriodoInicial = TxtFechaInicio.getText();
		//PeriodoFinal = TxtFechaFin.getText();
                
                
		new Visualizar().setVisible(true);
                this.setVisible (false);
               }
                else
                {
		//System.out.println("No cargo correctamente los datos, reintente");
                javax.swing.JOptionPane mensaje = new javax.swing.JOptionPane();
                mensaje.showMessageDialog(null, "La fecha ingresada no es válida", "Error al ingresar fecha", mensaje.ERROR_MESSAGE);
                }
                    
	//	System.out.println(PeriodoInicial);

	//	System.out.println(PeriodoFinal);
                }
                
               
                
  

    }//GEN-LAST:event_BtnTotalizarPisoActionPerformed

    private void TxtFechaFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFechaFinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFechaFinActionPerformed

    private void TxtFechaInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFechaInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFechaInicioActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reportesEnTiempoDePedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reportesEnTiempoDePedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reportesEnTiempoDePedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reportesEnTiempoDePedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reportesEnTiempoDePedido().setVisible(true);
                              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSalir;
    private javax.swing.JButton BtnTotalizarPiso;
    private javax.swing.JButton BtnTotalizarSector;
    private javax.swing.JButton BtnVisualizarSectorPiso;
    private javax.swing.JCheckBox CheckCancelado;
    private javax.swing.JCheckBox CheckEnPreparacion;
    private javax.swing.JCheckBox CheckEntregado;
    private javax.swing.JCheckBox CheckListoParaServir;
    private javax.swing.JCheckBox CheckNotificado;
    private javax.swing.JCheckBox CheckPendientePreparacion;
    private javax.swing.JCheckBox CheckPlantaBaja;
    private javax.swing.JCheckBox CheckPrimerPiso;
    private javax.swing.JCheckBox CheckSegundoPiso;
    private javax.swing.JTextField TxtFechaFin;
    private javax.swing.JTextField TxtFechaInicio;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
