package com.dsi.builder.front;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import com.dsi.builder.back.business.GestorReportesDeTiemposEnPedido;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Diego Delgado
 */
public class Visualizar extends javax.swing.JFrame {

    /**
     * Creates new form Visualizar
     */
    GestorReportesDeTiemposEnPedido gestor;
    
    public Visualizar(GestorReportesDeTiemposEnPedido gestor) {
        initComponents();
        this.gestor = gestor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnImprimir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        BtnCancelar = new javax.swing.JButton();
        BtnPDF = new javax.swing.JButton();
        BtnExcel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnImprimir.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        BtnImprimir.setText("Imprimir");
        BtnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnImprimirActionPerformed(evt);
            }
        });
        getContentPane().add(BtnImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 90, 30));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Elija una opción para visualizar:");
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        BtnCancelar.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 130, 40));

        BtnPDF.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        BtnPDF.setText("PDF");
        BtnPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPDFActionPerformed(evt);
            }
        });
        getContentPane().add(BtnPDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 90, 30));

        BtnExcel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        BtnExcel.setText("Excel");
        BtnExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExcelActionPerformed(evt);
            }
        });
        getContentPane().add(BtnExcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 90, 30));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pdf.jpg"))); // NOI18N
        jLabel5.setToolTipText("");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 70, 90));
        jLabel5.getAccessibleContext().setAccessibleName("img_PDF");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/excel.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, 90));
        jLabel8.getAccessibleContext().setAccessibleName("img_Excel");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/print.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 70, -1));
        jLabel9.getAccessibleContext().setAccessibleName("img_Printer");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FONDO.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 280));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pdf.jpg"))); // NOI18N
        jLabel7.setToolTipText("");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 70, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        if (JOptionPane.showConfirmDialog(rootPane, "¿Desea cancelar la generación de reporte?",
                "Salir de Generación de Reportes", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
        this.setVisible (false);
        reportesEnTiempoDePedido R = new reportesEnTiempoDePedido();
        R.setVisible (true);
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void BtnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnImprimirActionPerformed
        if (JOptionPane.showConfirmDialog(rootPane, "¿Desea imprimir el reporte?",
                "Generación de Reportes", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
            JOptionPane.showConfirmDialog(null, "Hey ! Esta parte no fue implementada :(",
                "Generación de Reportes - Excel", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_BtnImprimirActionPerformed

    private void BtnPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPDFActionPerformed
        if (JOptionPane.showConfirmDialog(rootPane, "¿Desea Generar el reporte en formato PDF?",
                "Generación de Reportes", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            try {
                this.gestor.generarReportePDF();
            } catch (Exception ex) {
                Logger.getLogger(reportesEnTiempoDePedido.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            if (Desktop.isDesktopSupported()) {
                try {
                    File myFile = new File("src/main/resources/output/ReporteDeTiemposDePedido.pdf");
                    Desktop.getDesktop().open(myFile);
                } catch (IOException ex) {
                    JOptionPane.showConfirmDialog(null, "UPS! Parece que no podés abrir el archivo...",
                "Generación de Reportes", JOptionPane.ERROR_MESSAGE); 
                }             
        this.setVisible(false);
        reportesEnTiempoDePedido main = new reportesEnTiempoDePedido();
        main.setVisible(true);
        }
        }
    }//GEN-LAST:event_BtnPDFActionPerformed

    private void BtnExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcelActionPerformed
        if (JOptionPane.showConfirmDialog(rootPane, "¿Desea Generar el reporte en formato EXCEL?",
                "Generación de Reportes", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
            JOptionPane.showConfirmDialog(null, "Hey ! Esta parte no fue implementada :(",
                "Generación de Reportes - Excel", JOptionPane.PLAIN_MESSAGE);
            
    }//GEN-LAST:event_BtnExcelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaConfirmar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnExcel;
    private javax.swing.JButton BtnImprimir;
    private javax.swing.JButton BtnPDF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
